/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as NonComplianceRouteImport } from './routes/non-compliance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as FarmsIndexRouteImport } from './routes/farms.index'
import { Route as AssessmentsIndexRouteImport } from './routes/assessments.index'
import { Route as ReportsReportIdRouteImport } from './routes/reports.$reportId'
import { Route as FarmsNewRouteImport } from './routes/farms.new'
import { Route as FarmsFarmIdRouteImport } from './routes/farms.$farmId'
import { Route as AssessmentsNewRouteImport } from './routes/assessments.new'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminChecklistRouteImport } from './routes/admin.checklist'
import { Route as AssessmentsIdIndexRouteImport } from './routes/assessments.$id.index'
import { Route as AssessmentsIdEditRouteImport } from './routes/assessments.$id.edit'

const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const NonComplianceRoute = NonComplianceRouteImport.update({
  id: '/non-compliance',
  path: '/non-compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmsIndexRoute = FarmsIndexRouteImport.update({
  id: '/farms/',
  path: '/farms/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsIndexRoute = AssessmentsIndexRouteImport.update({
  id: '/assessments/',
  path: '/assessments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsReportIdRoute = ReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmsNewRoute = FarmsNewRouteImport.update({
  id: '/farms/new',
  path: '/farms/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmsFarmIdRoute = FarmsFarmIdRouteImport.update({
  id: '/farms/$farmId',
  path: '/farms/$farmId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsNewRoute = AssessmentsNewRouteImport.update({
  id: '/assessments/new',
  path: '/assessments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChecklistRoute = AdminChecklistRouteImport.update({
  id: '/admin/checklist',
  path: '/admin/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsIdIndexRoute = AssessmentsIdIndexRouteImport.update({
  id: '/assessments/$id/',
  path: '/assessments/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsIdEditRoute = AssessmentsIdEditRouteImport.update({
  id: '/assessments/$id/edit',
  path: '/assessments/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/follow-ups': typeof FollowUpsRoute
  '/login': typeof LoginRoute
  '/non-compliance': typeof NonComplianceRoute
  '/supervisor': typeof SupervisorRoute
  '/admin/checklist': typeof AdminChecklistRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/farms/$farmId': typeof FarmsFarmIdRoute
  '/farms/new': typeof FarmsNewRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/assessments/': typeof AssessmentsIndexRoute
  '/farms/': typeof FarmsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/assessments/$id/edit': typeof AssessmentsIdEditRoute
  '/assessments/$id/': typeof AssessmentsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/follow-ups': typeof FollowUpsRoute
  '/login': typeof LoginRoute
  '/non-compliance': typeof NonComplianceRoute
  '/supervisor': typeof SupervisorRoute
  '/admin/checklist': typeof AdminChecklistRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/farms/$farmId': typeof FarmsFarmIdRoute
  '/farms/new': typeof FarmsNewRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/assessments': typeof AssessmentsIndexRoute
  '/farms': typeof FarmsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/assessments/$id/edit': typeof AssessmentsIdEditRoute
  '/assessments/$id': typeof AssessmentsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/follow-ups': typeof FollowUpsRoute
  '/login': typeof LoginRoute
  '/non-compliance': typeof NonComplianceRoute
  '/supervisor': typeof SupervisorRoute
  '/admin/checklist': typeof AdminChecklistRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/farms/$farmId': typeof FarmsFarmIdRoute
  '/farms/new': typeof FarmsNewRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/assessments/': typeof AssessmentsIndexRoute
  '/farms/': typeof FarmsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/assessments/$id/edit': typeof AssessmentsIdEditRoute
  '/assessments/$id/': typeof AssessmentsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/follow-ups'
    | '/login'
    | '/non-compliance'
    | '/supervisor'
    | '/admin/checklist'
    | '/admin/settings'
    | '/admin/users'
    | '/assessments/new'
    | '/farms/$farmId'
    | '/farms/new'
    | '/reports/$reportId'
    | '/assessments/'
    | '/farms/'
    | '/reports/'
    | '/assessments/$id/edit'
    | '/assessments/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/follow-ups'
    | '/login'
    | '/non-compliance'
    | '/supervisor'
    | '/admin/checklist'
    | '/admin/settings'
    | '/admin/users'
    | '/assessments/new'
    | '/farms/$farmId'
    | '/farms/new'
    | '/reports/$reportId'
    | '/assessments'
    | '/farms'
    | '/reports'
    | '/assessments/$id/edit'
    | '/assessments/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/follow-ups'
    | '/login'
    | '/non-compliance'
    | '/supervisor'
    | '/admin/checklist'
    | '/admin/settings'
    | '/admin/users'
    | '/assessments/new'
    | '/farms/$farmId'
    | '/farms/new'
    | '/reports/$reportId'
    | '/assessments/'
    | '/farms/'
    | '/reports/'
    | '/assessments/$id/edit'
    | '/assessments/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FollowUpsRoute: typeof FollowUpsRoute
  LoginRoute: typeof LoginRoute
  NonComplianceRoute: typeof NonComplianceRoute
  SupervisorRoute: typeof SupervisorRoute
  AdminChecklistRoute: typeof AdminChecklistRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AssessmentsNewRoute: typeof AssessmentsNewRoute
  FarmsFarmIdRoute: typeof FarmsFarmIdRoute
  FarmsNewRoute: typeof FarmsNewRoute
  ReportsReportIdRoute: typeof ReportsReportIdRoute
  AssessmentsIndexRoute: typeof AssessmentsIndexRoute
  FarmsIndexRoute: typeof FarmsIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  AssessmentsIdEditRoute: typeof AssessmentsIdEditRoute
  AssessmentsIdIndexRoute: typeof AssessmentsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/non-compliance': {
      id: '/non-compliance'
      path: '/non-compliance'
      fullPath: '/non-compliance'
      preLoaderRoute: typeof NonComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farms/': {
      id: '/farms/'
      path: '/farms'
      fullPath: '/farms/'
      preLoaderRoute: typeof FarmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/': {
      id: '/assessments/'
      path: '/assessments'
      fullPath: '/assessments/'
      preLoaderRoute: typeof AssessmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$reportId': {
      id: '/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof ReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farms/new': {
      id: '/farms/new'
      path: '/farms/new'
      fullPath: '/farms/new'
      preLoaderRoute: typeof FarmsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farms/$farmId': {
      id: '/farms/$farmId'
      path: '/farms/$farmId'
      fullPath: '/farms/$farmId'
      preLoaderRoute: typeof FarmsFarmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/new': {
      id: '/assessments/new'
      path: '/assessments/new'
      fullPath: '/assessments/new'
      preLoaderRoute: typeof AssessmentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/checklist': {
      id: '/admin/checklist'
      path: '/admin/checklist'
      fullPath: '/admin/checklist'
      preLoaderRoute: typeof AdminChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/$id/': {
      id: '/assessments/$id/'
      path: '/assessments/$id'
      fullPath: '/assessments/$id/'
      preLoaderRoute: typeof AssessmentsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/$id/edit': {
      id: '/assessments/$id/edit'
      path: '/assessments/$id/edit'
      fullPath: '/assessments/$id/edit'
      preLoaderRoute: typeof AssessmentsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FollowUpsRoute: FollowUpsRoute,
  LoginRoute: LoginRoute,
  NonComplianceRoute: NonComplianceRoute,
  SupervisorRoute: SupervisorRoute,
  AdminChecklistRoute: AdminChecklistRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AssessmentsNewRoute: AssessmentsNewRoute,
  FarmsFarmIdRoute: FarmsFarmIdRoute,
  FarmsNewRoute: FarmsNewRoute,
  ReportsReportIdRoute: ReportsReportIdRoute,
  AssessmentsIndexRoute: AssessmentsIndexRoute,
  FarmsIndexRoute: FarmsIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  AssessmentsIdEditRoute: AssessmentsIdEditRoute,
  AssessmentsIdIndexRoute: AssessmentsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
